### ISSUE TITLE
Nesting multiple tables ex. below

### ISSUE THREAD

**Issue by AMDAOFF** [acro5piano/knex-with-relations#10]
Hi, thanks for the great library. Saved me alot of time.

I just wish that nesting multiple tabls in one query were possible, or is it?

I have tried running this query ex. 

```
let listings = await this.dbConnection.table("listings")
                .select('listings.*')
                .innerJoin("cars", "listings.car_id", "cars.id")
                .innerJoin("car_images", "cars.id", "car_images.car_id")
                .where("cars.body_type", category_id)
                .where("listings.deleted", 0)
                .withHasManyRelation(this.dbConnection('car_images'), 'cars.id', 'car_id')
                .withHasOneRelation(this.dbConnection('cars'), 'car_id', 'id')
```

But when i try to run the code i simply cannot run withHadManyRelation and withHasOneRelation in the same query. Am i just too lazy to understand or does the library not support this?

**Comment by acro5piano** [comment]
Hi, thank you for reporting the issue.

> i simply cannot run withHadManyRelation and withHasOneRelation in the same query

Can you elaborate your error in more detail? Is there any error output, or nothing happens?

**Comment by AMDAOFF** [comment]
I got an error that said that ".withHasOneRelation" is nut a function.

When running the code today it seemed to work without errors. Do not know why tho... but it does not return anything (Guess i need to see if that is something in the DB design)

**Comment by acro5piano** [comment]
Hmm, the code will execute the query immediately, so it cannot be chained I guess... If you have any trouble, feel free to re-open this issue.

https://github.com/acro5piano/knex-with-relations/blob/main/src/knex-extends/withHasManyRelation.ts#L31
